FROM openjdk:11.0-oracle
ADD ./target/jwtauthentication-0.0.1-SNAPSHOT.jar /usr/src/jwtauthentication-0.0.1-SNAPSHOT.jar
WORKDIR usr/src
ENTRYPOINT ["java","-jar","jwtauthentication-0.0.1-SNAPSHOT.jar"]

